name: Push Auth Dev
on:
  workflow_dispatch:
  # push:

concurrency:
  group: wbt_dev
  cancel-in-progress: true

jobs:
  job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: ${{ secrets.RCLONE_CONFIG }}

      # - uses: browser-actions/setup-chrome@v2

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Environment
        run: |
          echo "${{ secrets.ENV_DEV }}" | base64 -d > .env

      - name: Bun
        run: bun i --production;bun run . pushauth

      - name: Sync
        run: bash ./.github/workflows/sync.sh push
