name: Deploy
on:
  push:
  workflow_dispatch:
  workflow_run:
    workflows: ["Push Auth", "Launcher"]
    types:
      - completed

concurrency:
  group: wbt
  cancel-in-progress: true

jobs:
  job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: ${{ secrets.RCLONE_CONFIG }}

      - name: Sync
        run: bash ./.github/workflows/sync.sh pull

      - uses: AnimMouse/setup-ffmpeg@v1
        with:
          version: master
        
      - uses: AnimMouse/setup-yt-dlp@v3

      - uses: browser-actions/setup-chrome@v2

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Environment
        run: |
          echo "${{ secrets.ENV }}" | base64 -d > .env

      - name: Bun
        run: bun i --production;bun run .
